### ISSUE TITLE
Linguagem do demo kkkk

### ISSUE THREAD

**Issue by robertoweller** [HashLDash/Wlang#1]
Escreve menos que python e mais rápido que C, acho que tem um dobra de espaço tempo kkkkk

**Comment by HashLDash** [comment]
Essa é a ideia. Mas o foco não é só velocidade, mas portabilidade! Basicamente preencher as lacunas que o Python deixa. Eu adoro Python, mas distribuir seu código para as plataformas, seja Windows, Linux, Android, IOs, RaspberryPI, Xbox360, etc é muito difícil ou inviável. Coisa que já é possível fazer com o Wlang, e com uma performance superior.

**Comment by HashLDash** [comment]
Vou fechar esse issue pois criei um lugar separado para comentários. É só navegar até as Discussões aqui do github.
